---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: postgres-external
spec:
  hosts:
  - postgres-external.apps.d9a0.example.opentlc.com
  ports:
  - number: 5432
    name: postgres
    protocol: TCP
  resolution: DNS
  location: MESH_EXTERNAL
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: postgres-egressgateway
spec:
  selector:
    istio: egressgateway
  servers:
  - port:
      number: 5432
      name: postgres
      protocol: TCP
    hosts:
    - postgres-external.apps.d9a0.example.opentlc.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: direct-pg-through-egress-gateway
spec:
  hosts:
  - postgres-external.apps.d9a0.example.opentlc.com
  gateways:
  - istio-egressgateway
  - mesh
  tcp:
  - match:
    - gateways:
      - mesh
      port: 5432
    route:
    - destination:
        host: istio-egressgateway.istio-system.svc.cluster.local
        subset: direct-pg-through-egress-gateway
        port:
          number: 5432
      weight: 100
  - match:
    - gateways:
      - istio-egressgateway
      port: 5432
    route:
    - destination:
        host: support1.d9a0.internal
        port:
          number: 5432
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: egressgateway-for-postgres
spec:
  host: istio-egressgateway.istio-system.svc.cluster.local
  subsets: 
  - name: direct-pg-through-egress-gateway
---
